server:
  port: 8081
  servlet:
    context-path: /roncoo

spring:
  application:
    name: roncoo

roncoo:
  swagger:
    enabled: true
    title: @name@
    description: @description@
    version: @version@
    author: lei.xu